### ISSUE TITLE
editor预览添加 vitepress 主题

### ISSUE THREAD

**Issue by shitou333111** [huyikai/local-cms#1]
非常棒的工具，而且可以预见会满足很多人的需求，因为还没有看到 vitepress 后端管理相关的工具。既然这个cms就是为vitepress配置的，那是不是可以将markdown预览配置成vitepress的样式？这样在后台编辑时就能保证渲染的和前端一样。

**Comment by huyikai** [comment]
> 非常棒的工具，而且可以预见会满足很多人的需求，因为还没有看到 vitepress 后端管理相关的工具。既然这个cms就是为vitepress配置的，那是不是可以将markdown预览配置成vitepress的样式？这样在后台编辑时就能保证渲染的和前端一样。

感谢赏识，这个工具因为我个人常用 vitepress 所以 cli 预置的是 vitepress 模板。但实际使用中是可以只管理目录中的 markdown 文件，与 vitepress 没有耦合。不过，你这个建议非常好，对于用户体验是有所提升的，我会考虑进行这方面的设计和改进。

**Comment by shitou333111** [comment]
> > 非常棒的工具，而且可以预见会满足很多人的需求，因为还没有看到 vitepress 后端管理相关的工具。既然这个cms就是为vitepress配置的，那是不是可以将markdown预览配置成vitepress的样式？这样在后台编辑时就能保证渲染的和前端一样。
> 
> 感谢赏识，这个工具因为我个人常用 vitepress 所以 cli 预置的是 vitepress 模板。但实际使用中是可以只管理目录中的 markdown 文件，与 vitepress 没有耦合。不过，你这个建议非常好，对于用户体验是有所提升的，我会考虑进行这方面的设计和改进。

如果cms做的好，会极大的改善vitepress（以及其他SSG）的体验。后台编辑器的丰富功能会方便内容编写，尤其是像我们这种非代码人员，写技术文档或者博客。下面是我查找到的相关工具：

[**v-md-editor**](https://code-farmer-i.github.io/vue-markdown-editor/zh/)

特点是基于vitepress的渲染规则和主题，可能较易引用。

![](https://github.com/huyikai/local-cms/assets/32065299/5cad040f-81ef-4051-82d0-d1e9e54e864f)

[**vue-quill**](https://vueup.github.io/vue-quill/)

特点是基于vue的富文本编辑器，功能比寻常md编辑器多，上面的链接就是其在vitepress中的直接使用demo。因为寻常md编辑器功能还是欠缺，比如常用的字体颜色 段落对齐等功能都没有。其中个人觉得最重要的是分栏功能，比如左侧是图片，右侧是正文。如果有了这个布局，加上md格式，应该能满足绝大部分的文档 博客 网站。

![](https://github.com/huyikai/local-cms/assets/32065299/2a645ff5-886c-40d8-a9f0-c96e3606e1a1)

如果给SSG加上后台功能，那么就可以将其变成像语雀/飞书/Notion/印象笔记一样的云文档/云笔记，下面是其他人类似想法的一些尝试：

https://github.com/pages-cms/pages-cms

[https://docs-demo.codex.so/about-this-demo](https://docs-demo.codex.so/about-this-demo)

以上只是讨论，不见得适合实现，希望能有帮助。

**Comment by huyikai** [comment]
@shitou333111 抱歉久等，终于在 0.0.24 版本中实现了前面提到的 vitepress 主题风格的编辑器，因为现有的markdown编辑器都没有很好的兼容 vitepress 渲染的效果，所以根据 vitepress 源码专门做了一个编辑器，能够完全还原 vitepress 渲染的效果。目前只开发了几个基本的编辑功能，之后会继续补充。
考虑到可能会有缓存，可以通过如下方式指定版本来使用。
```sh
npx @huyikai/local-cms@0.0.24 init
```
